# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7ae8c7b4-9729-468e-a0b6-833f8cce4abb";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-7ae8c7b4-9729-468e-a0b6-833f8cce4abb".device = "/dev/disk/by-uuid/7ae8c7b4-9729-468e-a0b6-833f8cce4abb";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-7ae8c7b4-9729-468e-a0b6-833f8cce4abb";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-7ae8c7b4-9729-468e-a0b6-833f8cce4abb";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/31D1-EE93";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6dbb1fe5-333b-4392-a81a-bd52ef847e3f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
