keys:
  - &admin_winston age1353vw9fqeqd84lppsmyhu5grpvhzcyyjse8tj59n5ht47ms7f5vq54v00q
  - &host_mac age1yfj9tkgnq40xmtf6atay0luat7rlu6eqa9q97j9pyk00mnhp434qhx3ke9

creation_rules:
  - path_regex: ^secrets/common\.yaml$
    key_groups:
      - age:
          - *admin_winston
          - *host_mac
