{ config, lib, ... }:
let
  cfg = config.lattice.hyprland;
in
{
  options.lattice.hyprland.extraConfig = lib.mkOption {
    type = lib.types.lines;
    default = "";
    example = lib.literalExpression ''
      '''
        hl.device({ name = "logitech-wireless-mouse-mx-master-3-1", accel_profile = "flat" })
      '''
    '';
    description = ''
      Lua run at the end of lattice's Hyprland config, so it wins over anything there:
      what belongs to this machine rather than to the distro -- an external monitor's
      workspaces, a mouse's device block. Written to /etc/xdg/hypr/lattice.lua, along
      with the rules lattice.display.monitors generates. The user's own
      ~/.config/hypr/local.lua runs after it.
    '';
  };

  ### HYPRLAND ###
  # The config is ./configs/hyprland.lua, at the /etc/xdg path Hyprland falls back to when
  # ~/.config/hypr/hyprland.lua is not there. It loadfile()s lattice.lua at the end, so an
  # empty one is left unwritten rather than written blank.
  config.environment.etc = {
    "xdg/hypr/hyprland.lua".source = ./configs/hyprland.lua;

    "xdg/hypr/lattice.lua" = lib.mkIf (cfg.extraConfig != "") {
      text = ''
        -- Generated by lattice, from lattice.hyprland.extraConfig and
        -- lattice.display.monitors (modules/nixos/desktop/hyprland.nix). Run at the end of
        -- /etc/xdg/hypr/hyprland.lua, so these win over the rules it sets itself.
        ${cfg.extraConfig}'';
    };
  };
}
