[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.cache/lattice/theme.qt6ct.conf
icon_theme=Papirus-Dark
standard_dialogs=default

[Fonts]
general="Noto Sans,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrains Mono,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
underline_shortcut=0
