{ config, lib, ... }:
let
  cfg = config.lattice.display;

  # hl.monitor takes mode and position as strings always, but scale as either a number or
  # the literal "auto" -- so the number goes in bare and everything else gets quoted.
  scaleOf = scale: if scale == "auto" then "\"auto\"" else scale;

  monitors = lib.concatStrings (
    lib.mapAttrsToList (output: m: ''

      hl.monitor({
          output   = "${output}",
          mode     = "${m.mode}",
          position = "${m.position}",
          scale    = ${scaleOf m.scale},
      })
    '') cfg.monitors
  );
in
{
  options.lattice.display.monitors = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          mode = lib.mkOption {
            type = lib.types.str;
            default = "preferred";
            example = "3024x1890@120";
            description = "Hyprland mode string.";
          };

          position = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "0x0";
            description = "Hyprland position string.";
          };

          scale = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "2.25";
            description = ''
              Hyprland scale, as the literal to write into the config -- a decimal, or
              "auto" to let Hyprland choose. A string rather than a float because Nix
              renders `2.25` as `2.250000`, which is valid Lua but unreadable.

              Two constraints, both of which Hyprland rejects at load with a silent
              fallback to 1 rather than an error:

              - The logical size the scale produces has to land on whole pixels, i.e.
                both `width / scale` and `height / scale` must come out integral.
              - Wayland carries fractional scales over wp_fractional_scale_v1 in 120ths,
                so the scale must be a multiple of 1/120. 2.25 (270/120) is fine; 2.52
                (302.4/120) is not, however evenly it divides the panel.
            '';
          };
        };
      }
    );

    default = { };
    example = lib.literalExpression ''{ "eDP-1".scale = "2.25"; }'';
    description = ''
      Per-output Hyprland monitor rules for this host, written to
      /etc/xdg/hypr/lattice.lua and loaded by ~/.dotfiles/hypr if it is there.

      Monitor rules are split this way because the two laptops both call their internal
      panel eDP-1 while wanting different scales, and ~/.dotfiles is one repo shared
      between them and macOS -- so an `output = "eDP-1"` rule written there would follow
      the wrong machine home. The generic defaults and the rules for monitors that can be
      told apart by description (the Samsung on the dock) stay in ~/.dotfiles; anything
      keyed on hardware that is host-specific belongs here.
    '';
  };

  options.lattice.display.sunsetTemperature = lib.mkOption {
    type = lib.types.ints.between 1000 6000;
    default = 4000;
    example = 3000;
    description = ''
      Colour temperature, in kelvin, that lattice-sunset switches the screen to -- the
      "on" end of the night-light toggle in modules/nixos/profiles/graphical.nix. The
      "off" end is hyprsunset's own 6000K, which is no filter at all.

      Per-host for the same reason the scales above are: the strength of the shift is a
      property of the panel, not of the setting. The Dell's sRGB panel reads 4000K as a
      clear warm cast; the MacBook's is wide-gamut and much brighter, so the same
      transform lands far weaker there and wants a lower number to match it.

      `hyprctl hyprsunset temperature <k>` tries a value on the running daemon without a
      rebuild, which is the way to pick one; the next lattice-sunset toggle returns to
      whatever is set here.
    '';
  };

  # Left unwritten when a host sets no overrides, which is what the `loadfile` guard in
  # ~/.dotfiles/hypr/hyprland.lua expects -- no file means its own defaults stand.
  config = lib.mkIf (cfg.monitors != { }) {
    environment.etc."xdg/hypr/lattice.lua".text = ''
      -- Generated by lattice, from lattice.display.monitors in modules/nixos/display.nix.
      -- Loaded at the end of ~/.dotfiles/hypr/hyprland.lua, so these win over the rules
      -- it sets itself.
      ${monitors}'';
  };
}
