{ config, lib, ... }:
let
  cfg = config.lattice.display;

  # hl.monitor takes mode and position as strings always, but scale as either a number or
  # the literal "auto" -- so the number goes in bare and everything else gets quoted.
  scaleOf = scale: if scale == "auto" then "\"auto\"" else scale;

  monitors = lib.concatStrings (
    lib.mapAttrsToList (output: m: ''

      hl.monitor({
          output   = "${output}",
          mode     = "${m.mode}",
          position = "${m.position}",
          scale    = ${scaleOf m.scale},
      })
    '') cfg.monitors
  );
in
{
  options.lattice.display.monitors = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          mode = lib.mkOption {
            type = lib.types.str;
            default = "preferred";
            example = "3024x1890@120";
            description = "Hyprland mode string.";
          };

          position = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "0x0";
            description = "Hyprland position string.";
          };

          scale = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "2.25";
            description = ''
              Hyprland scale, as the literal to write into the config -- a decimal, or
              "auto" to let Hyprland choose. A string rather than a float because Nix
              renders `2.25` as `2.250000`, which is valid Lua but unreadable.

              Two constraints, both of which Hyprland rejects at load with a silent
              fallback to 1 rather than an error:

              - The logical size the scale produces has to land on whole pixels, i.e.
                both `width / scale` and `height / scale` must come out integral.
              - Wayland carries fractional scales over wp_fractional_scale_v1 in 120ths,
                so the scale must be a multiple of 1/120. 2.25 (270/120) is fine; 2.52
                (302.4/120) is not, however evenly it divides the panel.
            '';
          };
        };
      }
    );

    default = { };
    example = lib.literalExpression ''{ "eDP-1".scale = "2.25"; }'';
    description = ''
      Per-output Hyprland monitor rules for this host, written to
      /etc/xdg/hypr/lattice.lua and loaded by ~/.dotfiles/hypr if it is there.

      Monitor rules are split this way because the two laptops both call their internal
      panel eDP-1 while wanting different scales, and ~/.dotfiles is one repo shared
      between them and macOS -- so an `output = "eDP-1"` rule written there would follow
      the wrong machine home. The generic defaults and the rules for monitors that can be
      told apart by description (the Samsung on the dock) stay in ~/.dotfiles; anything
      keyed on hardware that is host-specific belongs here.
    '';
  };

  # Left unwritten when a host sets no overrides, which is what the `loadfile` guard in
  # ~/.dotfiles/hypr/hyprland.lua expects -- no file means its own defaults stand.
  config = lib.mkIf (cfg.monitors != { }) {
    environment.etc."xdg/hypr/lattice.lua".text = ''
      -- Generated by lattice, from lattice.display.monitors in modules/nixos/display.nix.
      -- Loaded at the end of ~/.dotfiles/hypr/hyprland.lua, so these win over the rules
      -- it sets itself.
      ${monitors}'';
  };
}
