{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.lattice.display;

  # hl.monitor takes mode and position as strings always, but scale as either a number or
  # the literal "auto" -- so the number goes in bare and everything else gets quoted.
  scaleOf = scale: if scale == "auto" then "\"auto\"" else scale;

  # A battery-aware rule picks its mode when it is evaluated, so the same text is right at
  # login, on a config reload and when lattice-battery-modes re-runs it after an unplug.
  modeOf =
    m:
    if m.batteryMode == null then
      "\"${m.mode}\""
    else
      "latticeOnBattery() and \"${m.batteryMode}\" or \"${m.mode}\"";

  rule = output: m: ''

    hl.monitor({
        output   = "${output}",
        mode     = ${modeOf m},
        position = "${m.position}",
        scale    = ${scaleOf m.scale},
    })
  '';

  partitioned = lib.partition (output: cfg.monitors.${output}.batteryMode == null) (
    lib.attrNames cfg.monitors
  );
  rulesFor = outputs: lib.concatMapStrings (output: rule output cfg.monitors.${output}) outputs;
  hasBatteryModes = partitioned.wrong != [ ];

  # On battery means at least one Mains supply exists and none of them is online, so a
  # machine with no Mains supply at all (a desktop) never counts as on battery. Read through
  # a shell because Lua has no directory listing; it runs once per evaluation, not per frame.
  #
  # Kept in a file of its own so lattice-battery-modes can hand exactly these rules to
  # `hyprctl eval` -- re-running every rule would also re-apply the external monitors on
  # each plug event.
  batteryRules = ''
    -- Generated by lattice, from lattice.display.monitors.<output>.batteryMode in
    -- modules/nixos/display.nix. Run by /etc/xdg/hypr/lattice.lua at load, and again by
    -- lattice-battery-modes through `hyprctl eval` whenever the charger comes or goes.
    local function latticeOnBattery()
        local p = io.popen([[for d in /sys/class/power_supply/*; do [ "$(cat "$d/type")" = Mains ] && cat "$d/online"; done 2>/dev/null]])
        if not p then return false end
        local states = p:read("a")
        p:close()
        return states:find("0") ~= nil and states:find("1") == nil
    end
    ${rulesFor partitioned.wrong}'';

  # Re-applies the battery-aware rules when the charger state changes. upower --monitor is
  # the event source because it subscribes to signals the ordinary way; busctl and
  # dbus-monitor both want to become a bus monitor, which the system bus refuses a user.
  # It prints on every battery tick too, so the Mains state is compared and only a change
  # reaches Hyprland.
  batteryModes = pkgs.writeShellApplication {
    name = "lattice-battery-modes";
    runtimeInputs = [
      pkgs.upower
      pkgs.hyprland
      pkgs.coreutils
    ];
    text = ''
      state() {
        for d in /sys/class/power_supply/*; do
          if [ "$(cat "$d/type" 2>/dev/null)" = Mains ]; then cat "$d/online"; fi
        done
      }

      # dofile rather than the file's text: hyprctl reads an argument starting with the
      # file's opening `--` comment as one of its own flags.
      apply() {
        hyprctl eval 'dofile("/etc/xdg/hypr/lattice-battery.lua")' >/dev/null || true
      }

      last=$(state)
      apply

      # stdbuf because upower writes through stdio, which block-buffers into a pipe and
      # would hold an unplug back until several kilobytes of battery ticks had followed it.
      stdbuf -oL upower --monitor | while read -r _; do
        now=$(state)
        if [ "$now" != "$last" ]; then
          last=$now
          apply
        fi
      done
    '';
  };
in
{
  options.lattice.display.monitors = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          mode = lib.mkOption {
            type = lib.types.str;
            default = "preferred";
            example = "3024x1890@120";
            description = "Hyprland mode string.";
          };

          batteryMode = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            example = "3024x1890@60";
            description = ''
              Mode to use instead of `mode` while the machine is on battery, or null to
              use `mode` always. Applied at load and again on every charger plug or unplug
              by the lattice-battery-modes user service.
            '';
          };

          position = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "0x0";
            description = "Hyprland position string.";
          };

          scale = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "2.25";
            description = ''
              Hyprland scale, as the literal to write into the config -- a decimal, or
              "auto" to let Hyprland choose. A string rather than a float because Nix
              renders `2.25` as `2.250000`, which is valid Lua but unreadable.

              Two constraints, both of which Hyprland rejects at load with a silent
              fallback to 1 rather than an error:

              - The logical size the scale produces has to land on whole pixels, i.e.
                both `width / scale` and `height / scale` must come out integral.
              - Wayland carries fractional scales over wp_fractional_scale_v1 in 120ths,
                so the scale must be a multiple of 1/120. 2.25 (270/120) is fine; 2.52
                (302.4/120) is not, however evenly it divides the panel.
            '';
          };
        };
      }
    );

    default = { };
    example = lib.literalExpression ''{ "eDP-1".scale = "2.25"; }'';
    description = ''
      Per-output Hyprland monitor rules for this host, written to
      /etc/xdg/hypr/lattice.lua and loaded by ~/.dotfiles/hypr if it is there.

      Monitor rules are split this way because the two laptops both call their internal
      panel eDP-1 while wanting different scales, and ~/.dotfiles is one repo shared
      between them and macOS -- so an `output = "eDP-1"` rule written there would follow
      the wrong machine home. The generic defaults and the rules for monitors that can be
      told apart by description (the Samsung on the dock) stay in ~/.dotfiles; anything
      keyed on hardware that is host-specific belongs here.
    '';
  };

  # The wallpaper is drawn to a canvas, not to a screen, and this is the canvas. The rule
  # the drawing depends on is in desktop/lib.nix: the canvas is sized at the screen's
  # *logical* resolution, so the mark comes out the same size against the UI on every
  # display, whatever each one's pixel count and scale. A canvas smaller than the logical
  # screen is not cropped or letterboxed -- hyprpaper scales it to cover -- it is magnified,
  # and everything on it with it. That is exactly what went wrong here: 1920x1080 on a
  # 2560x1440 logical monitor blew the lattice up by a third.
  #
  # So these are per host, like the scales above and for the same reason: they are a
  # property of the screens in front of this machine. `width`/`height` are the logical size
  # -- a monitor's pixels divided by its Hyprland scale -- and `scale` is how many output
  # pixels each canvas unit is rasterised to, so width * scale should land on the panel's
  # real pixel width. Read both off `hyprctl monitors -j`.
  options.lattice.display.canvas = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          width = lib.mkOption {
            type = lib.types.ints.positive;
            description = "Canvas width, in logical pixels.";
          };

          height = lib.mkOption {
            type = lib.types.ints.positive;
            description = "Canvas height, in logical pixels.";
          };

          scale = lib.mkOption {
            type = lib.types.numbers.positive;
            default = 2;
            example = 2.25;
            description = ''
              Output pixels per canvas unit. A float is fine here, unlike the monitor scale
              above: this one is arithmetic rather than a literal, and the multiplication is
              floored before it reaches the rasteriser.
            '';
          };
        };
      }
    );

    default = {
      # Two 16:10-ish stand-ins, for a host that has not measured its own. They are what
      # this was before it was per host, and they are wrong for any specific screen.
      panel = {
        width = 1200;
        height = 750;
        scale = 3;
      };
      desk = {
        width = 1920;
        height = 1080;
        scale = 2;
      };
    };

    description = ''
      The two wallpaper canvases: `panel` for an internal display, `desk` for anything else.
      Every wallpaper in the pool is drawn once at each, and lattice-wallpaper picks between
      them per output by connector name.
    '';
  };

  options.lattice.display.notificationOutput = lib.mkOption {
    type = lib.types.str;
    default = "";
    example = "HDMI-A-1";
    description = ''
      Output that mako pins notification banners to, written as an `output=` line into
      /etc/xdg/mako/lattice-output and included by the mako config in ~/.dotfiles. Empty
      leaves mako on its own default, which is the focused output.

      Naming the external monitor here is the whole of "on the monitor when it is docked,
      on the laptop when it is not": an output that is not connected is not an error to
      mako, it falls back to the focused one, so there is nothing to watch the hotplug and
      no second state to keep in step. Measured both ways on the Mac while docked, with
      focus parked on the Samsung -- `output=eDP-1` put the banner on the panel, so a name
      that exists beats focus, and a deliberately bogus name put it back on the focused
      output rather than dropping it.

      Per-host because mako matches the connector name and nothing else. `desc:` strings,
      which is how ~/.dotfiles/hypr tells this same Samsung apart on either laptop without
      naming a port, are not understood here -- mako reads one as a name, misses, and
      quietly falls back to the focused output -- and the monitor is HDMI-A-1 on the Mac
      but a DP connector on the Dell, so there is no one name to share.
    '';
  };

  options.lattice.display.sunsetTemperature = lib.mkOption {
    type = lib.types.ints.between 1000 6000;
    default = 4000;
    example = 3000;
    description = ''
      Colour temperature, in kelvin, that lattice-sunset switches the screen to -- the
      "on" end of the night-light toggle in modules/nixos/desktop/session.nix. The
      "off" end is hyprsunset's own 6000K, which is no filter at all.

      Per-host for the same reason the scales above are: the strength of the shift is a
      property of the panel, not of the setting. The Dell's sRGB panel reads 4000K as a
      clear warm cast; the MacBook's is wide-gamut and much brighter, so the same
      transform lands far weaker there and wants a lower number to match it.

      `hyprctl hyprsunset temperature <k>` tries a value on the running daemon without a
      rebuild, which is the way to pick one; the next lattice-sunset toggle returns to
      whatever is set here.
    '';
  };

  options.lattice.display.webZoom = lib.mkOption {
    type = lib.types.numbers.between 0.5 2.0;
    default = 1.0;
    example = 0.8;
    description = ''
      Zoom for lattice's own pages shown outside Firefox -- the keybinding cheatsheet, in a
      Chromium app window -- so they come out the size Firefox draws pages at on this host.
      Chromium follows the output's scale with nothing on top, while Firefox carries a
      per-host factor: devPixelsPerPx 1.1 on the Dell, and on the Mac the 80% default zoom
      that lives in the Firefox profile rather than in any pref (hosts/mac/default.nix).
      This is that factor, applied by the page itself as CSS zoom.
    '';
  };

  config = lib.mkMerge [
    # Written even when the host sets nothing, unlike the hypr file below: ~/.dotfiles/mako
    # includes this unconditionally, and mako has no `loadfile` guard to hide a missing one
    # behind -- an include that is not there fails the whole config, not just the include.
    # Measured: `makoctl reload` answers "Unable to parse configuration file" and the daemon
    # carries on with whatever it last parsed, so the failure is silent on screen.
    {
      environment.etc."xdg/mako/lattice-output".text = ''
        # Generated by lattice, from lattice.display.notificationOutput in
        # modules/nixos/display.nix. Included from the global section of the mako config
        # in ~/.dotfiles, and a global setting is what it stays: mako resumes the
        # including file's section afterwards rather than carrying this file's context on.
      ''
      + lib.optionalString (cfg.notificationOutput != "") ''
        output=${cfg.notificationOutput}
      '';
    }

    # Left unwritten when a host sets no overrides, which is what the `loadfile` guard in
    # ~/.dotfiles/hypr/hyprland.lua expects -- no file means its own defaults stand.
    (lib.mkIf (cfg.monitors != { }) {
      environment.etc."xdg/hypr/lattice.lua".text = ''
        -- Generated by lattice, from lattice.display.monitors in modules/nixos/display.nix.
        -- Loaded at the end of ~/.dotfiles/hypr/hyprland.lua, so these win over the rules
        -- it sets itself.
        ${rulesFor partitioned.right}''
      + lib.optionalString hasBatteryModes ''

        dofile("/etc/xdg/hypr/lattice-battery.lua")
      '';
    })

    (lib.mkIf hasBatteryModes {
      environment.etc."xdg/hypr/lattice-battery.lua".text = batteryRules;

      systemd.user.services.lattice-battery-modes = {
        description = "Switch battery-aware monitor modes on charger changes";
        partOf = [ "graphical-session.target" ];
        after = [ "graphical-session.target" ];
        wantedBy = [ "graphical-session.target" ];
        onFailure = lib.optional config.services.graphical-desktop.enable "lattice-notify-failure@%n.service";
        serviceConfig = {
          ExecStart = lib.getExe batteryModes;
          Restart = "on-failure";
        };
      };
    })
  ];
}
